<?php
use Illuminate\Database\Seeder;
use App\Models\DiscountCoupon;
use App\Models\Product;

class DiscountCouponsTableSeeder extends Seeder
{

    public function run()
    {
        DiscountCoupon::truncate();
        $coupons = [
            [
                'is_active'         =>  true,
                'coupon_code'       => 'o7bRwsZJ',
                'name'              => 'Flat $1',
                'discount_type'     => 'dollars',
                'discount_percent'  => 0,
                'discount_amount'   => 1,
                'single_use'        => true,
                'duration'          => 'single_use',
                'cycles'            => null,
                'temporal_unit'     => null,
                'temporal_amount'   => null,
                'product_id'        => null,
                'plan_code'         => null,
                'type'              => DiscountCoupon::SETUP_FEE_COUPON,
            ],
            [
                'is_active'         =>  true,
                'coupon_code'       => 'LsFTjuBf',
                'name'              => 'Waive 50%',
                'discount_type'     => 'percent',
                'discount_percent'  => 50,
                'discount_amount'   => 0,
                'single_use'        => true,
                'duration'          => 'single_use',
                'cycles'            => null,
                'temporal_unit'     => null,
                'temporal_amount'   => null,
                'product_id'        => null,
                'plan_code'         => null,
                'type'              => DiscountCoupon::SETUP_FEE_COUPON,
            ],
            [
                'is_active'         =>  false,
                'coupon_code'       => 'smByB8xK',
                'name'              => 'Basic plan for $1 - Valid for 2 weeks',
                'discount_type'     => 'dollars',
                'discount_percent'  => 0,
                'discount_amount'   => 58.00,
                'single_use'        => false,
                'duration'          => 'temporal',
                'cycles'            => 1,
                'temporal_unit'     => 'week',
                'temporal_amount'   => 2,
                'product_id'        => Product::PRODUCT_JOBPROGRESS,
                'plan_code'         => 'jp-1dollar-2weeks',
                'type'              => DiscountCoupon::MONTHLY_FEE_COUPON,
            ],
            [
                'is_active'         =>  false,
                'coupon_code'       => 'lhsysmh8',
                'name'              => 'Basic plan for $1 - Valid for 1 month',
                'discount_type'     => 'dollars',
                'discount_percent'  => 0,
                'discount_amount'   => 58.00,
                'single_use'        => false,
                'duration'          => 'temporal',
                'cycles'            => 1,
                'temporal_unit'     => 'month',
                'temporal_amount'   => 2,
                'product_id'        => Product::PRODUCT_JOBPROGRESS,
                'plan_code'         => 'jp-1dollar',
                'type'              => DiscountCoupon::MONTHLY_FEE_COUPON,
            ],
            [
                'is_active'         =>  false,
                'coupon_code'       => 'for78bsg',
                'name'              => 'Basic plan for $1 - Valid for 2 month',
                'discount_type'     => 'dollars',
                'discount_percent'  => 0,
                'discount_amount'   => 58.00,
                'single_use'        => false,
                'duration'          => 'temporal',
                'cycles'            => 2,
                'temporal_unit'     => 'month',
                'temporal_amount'   => 2,
                'product_id'        => Product::PRODUCT_JOBPROGRESS,
                'plan_code'         => 'jp-1dollar',
                'type'              => DiscountCoupon::MONTHLY_FEE_COUPON,
            ],
            [
                'is_active'         =>  false,
                'coupon_code'       => 'yt7xhf9j',
                'name'              => 'Basic plan for $1 - Valid for 3 month',
                'discount_type'     => 'dollars',
                'discount_percent'  => 0,
                'discount_amount'   => 58.00,
                'single_use'        => false,
                'duration'          => 'temporal',
                'cycles'            => 3,
                'temporal_unit'     => 'month',
                'temporal_amount'   => 3,
                'product_id'        => Product::PRODUCT_JOBPROGRESS,
                'plan_code'         => 'jp-1dollar',
                'type'              => DiscountCoupon::MONTHLY_FEE_COUPON,
            ],
            [
                'is_active'         =>  false,
                'coupon_code'       => 'Yvq2c4N2',
                'name'              => 'Plus plan for $1 - Valid for 2 weeks',
                'discount_type'     => 'dollars',
                'discount_percent'  => 0,
                'discount_amount'   => 78.00,
                'single_use'        => false,
                'duration'          => 'temporal',
                'cycles'            => 1,
                'temporal_unit'     => 'week',
                'temporal_amount'   => 2,
                'product_id'        => Product::PRODUCT_JOBPROGRESS_PLUS,
                'plan_code'         => 'jp-plus-1dollar-2weeks',
                'type'              => DiscountCoupon::MONTHLY_FEE_COUPON,
            ],
            [
                'is_active'         =>  true,
                'coupon_code'       => 'hdsc7kgd',
                'name'              => 'Plus plan for $1 - Valid for 1 month',
                'discount_type'     => 'dollars',
                'discount_percent'  => 0,
                'discount_amount'   => 78.00,
                'single_use'        => false,
                'duration'          => 'temporal',
                'cycles'            => 1,
                'temporal_unit'     => 'month',
                'temporal_amount'   => 1,
                'product_id'        => Product::PRODUCT_JOBPROGRESS_PLUS,
                'plan_code'         => 'jp-plus-1dollar',
                'type'              => DiscountCoupon::MONTHLY_FEE_COUPON,
            ],
            [
                'is_active'         =>  true,
                'coupon_code'       => 'yk9pevpj',
                'name'              => 'Plus plan for $1 - Valid for 2 month',
                'discount_type'     => 'dollars',
                'discount_percent'  => 0,
                'discount_amount'   => 78.00,
                'single_use'        => false,
                'duration'          => 'temporal',
                'cycles'            => 2,
                'temporal_unit'     => 'month',
                'temporal_amount'   => 2,
                'product_id'        => Product::PRODUCT_JOBPROGRESS_PLUS,
                'plan_code'         => 'jp-plus-1dollar',
                'type'              => DiscountCoupon::MONTHLY_FEE_COUPON,
            ],
            [
                'is_active'         =>  true,
                'coupon_code'       => 'fhuetovj',
                'name'              => 'Plus plan for $1 - Valid for 3 month',
                'discount_type'     => 'dollars',
                'discount_percent'  => 0,
                'discount_amount'   => 78.00,
                'single_use'        => false,
                'duration'          => 'temporal',
                'cycles'            => 3,
                'temporal_unit'     => 'month',
                'temporal_amount'   => 3,
                'product_id'        => Product::PRODUCT_JOBPROGRESS_PLUS,
                'plan_code'         => 'jp-plus-1dollar',
                'type'              => DiscountCoupon::MONTHLY_FEE_COUPON,
            ],
            [
                'is_active'         =>  true,
                'coupon_code'       => 'eMnkwgRe',
                'name'              => 'GAF Plus plan for $1 - Valid for 1 month',
                'discount_type'     => 'dollars',
                'discount_percent'  => 0,
                'discount_amount'   => 49.00,
                'single_use'        => false,
                'duration'          => 'temporal',
                'cycles'            => 1,
                'temporal_unit'     => 'month',
                'temporal_amount'   => 1,
                'product_id'        => Product::PRODUCT_GAF_PLUS,
                'plan_code'         => 'gaf-plus-1dollar',
                'type'              => DiscountCoupon::MONTHLY_FEE_COUPON,
            ],
            [
                'is_active'         =>  true,
                'coupon_code'       => 'pAvsSaxC',
                'name'              => 'GAF Plus plan for $1 - Valid for 2 month',
                'discount_type'     => 'dollars',
                'discount_percent'  => 0,
                'discount_amount'   => 49.00,
                'single_use'        => false,
                'duration'          => 'temporal',
                'cycles'            => 2,
                'temporal_unit'     => 'month',
                'temporal_amount'   => 2,
                'product_id'        => Product::PRODUCT_GAF_PLUS,
                'plan_code'         => 'gaf-plus-1dollar',
                'type'              => DiscountCoupon::MONTHLY_FEE_COUPON,
            ],
            [
                'is_active'         =>  true,
                'coupon_code'       => 'M3dARY6T',
                'name'              => 'Zero Setup Fee',
                'discount_type'     => 'dollars',
                'discount_percent'  => 0,
                'discount_amount'   => 0,
                'single_use'        => true,
                'duration'          => 'single_use',
                'cycles'            => null,
                'temporal_unit'     => null,
                'temporal_amount'   => null,
                'product_id'        => Product::PRODUCT_GAF_PLUS,
                'plan_code'         => null,
                'type'              => DiscountCoupon::SETUP_FEE_COUPON,
                'is_offer'          => true,
                'start_date_time'   => '2017-03-01 00:00:00',
                'end_date_time'     => '2017-03-31 23:59:59',
            ],
            [
                'is_active'         =>  true,
                'coupon_code'       => 'hLVjjqGy',
                'name'              => '14 days trial',
                'discount_type'     => 'trial',
                'discount_percent'  => 0,
                'discount_amount'   => 0,
                'single_use'        => true,
                'duration'          => 'temporal',
                'cycles'            => 0,
                'temporal_unit'     => 'days',
                'temporal_amount'   => 14,
                'product_id'        => null,
                'plan_code'         => null,
                'type'              => DiscountCoupon::TRIAL_COUPON,
            ],
            [
                'is_active'         =>  true,
                'coupon_code'       => 'Ynvarxt6',
                'name'              => 'Waive $500',
                'discount_type'     => 'dollars',
                'discount_percent'  => 0,
                'discount_amount'   => 995,
                'single_use'        => true,
                'duration'          => 'single_use',
                'cycles'            => null,
                'temporal_unit'     => null,
                'temporal_amount'   => null,
                'product_id'        => Product::PRODUCT_JOBPROGRESS_PLUS,
                'plan_code'         => null,
                'type'              => DiscountCoupon::SETUP_FEE_COUPON,
            ],
        ];

        foreach ($coupons as $key => $coupon) {
            DiscountCoupon::create($coupon);
        }
    }
}
