<?php

use Illuminate\Database\Seeder;
use App\Models\FinancialAccountTypes;

class FinancialAccountTypesTableSeeder extends Seeder {

	public function run()
	{
		FinancialAccountTypes::truncate();

		$accountTypes = [
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Bank',
				'account_type_display_name'		=>	'Bank',
				'account_sub_type'				=>	'CashOnHand',
				'account_sub_type_display_name'	=>	'Cash on hand',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Bank',
				'account_type_display_name'		=>	'Bank',
				'account_sub_type'				=>	'Checking',
				'account_sub_type_display_name'	=>	'Checking',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Bank',
				'account_type_display_name'		=>	'Bank',
				'account_sub_type'				=>	'MoneyMarket',
				'account_sub_type_display_name'	=>	'Money Market',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Bank',
				'account_type_display_name'		=>	'Bank',
				'account_sub_type'				=>	'RentsHeldInTrust',
				'account_sub_type_display_name'	=>	'Rents Held in Trust',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Bank',
				'account_type_display_name'		=>	'Bank',
				'account_sub_type'				=>	'Savings',
				'account_sub_type_display_name'	=>	'Savings',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Bank',
				'account_type_display_name'		=>	'Bank',
				'account_sub_type'				=>	'TrustAccounts',
				'account_sub_type_display_name'	=>	'Trust account',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Other Current Asset',
				'account_type_display_name'		=>	'Other Current Assets',
				'account_sub_type'				=>	'AllowanceForBadDebts',
				'account_sub_type_display_name'	=>	'Allowance For Bad Debts',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Other Current Asset',
				'account_type_display_name'		=>	'Other Current Assets',
				'account_sub_type'				=>	'DevelopmentCosts',
				'account_sub_type_display_name'	=>	'Development Costs',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Other Current Asset',
				'account_type_display_name'		=>	'Other Current Assets',
				'account_sub_type'				=>	'EmployeeCashAdvances',
				'account_sub_type_display_name'	=>	'Employee Cash Advances',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Other Current Asset',
				'account_type_display_name'		=>	'Other Current Assets',
				'account_sub_type'				=>	'OtherCurrentAssets',
				'account_sub_type_display_name'	=>	'Other Current Assets',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Other Current Asset',
				'account_type_display_name'		=>	'Other Current Assets',
				'account_sub_type'				=>	'Investment_MortgageRealEstateLoans',
				'account_sub_type_display_name'	=>	'Investment - Mortgage/Real Estate Loans',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Other Current Asset',
				'account_type_display_name'		=>	'Other Current Assets',
				'account_sub_type'				=>	'Investment_Other',
				'account_sub_type_display_name'	=>	'Investments - Other',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Other Current Asset',
				'account_type_display_name'		=>	'Other Current Assets',
				'account_sub_type'				=>	'Inventory',
				'account_sub_type_display_name'	=>	'Inventory',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Other Current Asset',
				'account_type_display_name'		=>	'Other Current Assets',
				'account_sub_type'				=>	'Investment_TaxExemptSecurities',
				'account_sub_type_display_name'	=>	'Investment - Tax-Exempt Securities',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Other Current Asset',
				'account_type_display_name'		=>	'Other Current Assets',
				'account_sub_type'				=>	'Investment_USGovernmentObligations',
				'account_sub_type_display_name'	=>	'Investment - US. Government Obligations',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Other Current Asset',
				'account_type_display_name'		=>	'Other Current Assets',
				'account_sub_type'				=>	'LoansToOfficers',
				'account_sub_type_display_name'	=>	'Loans To Officers',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Other Current Asset',
				'account_type_display_name'		=>	'Other Current Assets',
				'account_sub_type'				=>	'LoansToOthers',
				'account_sub_type_display_name'	=>	'Loans To Others',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Other Current Asset',
				'account_type_display_name'		=>	'Other Current Assets',
				'account_sub_type'				=>	'LoansToStockholders',
				'account_sub_type_display_name'	=>	'Loans To Stockholders',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Other Current Asset',
				'account_type_display_name'		=>	'Other Current Assets',
				'account_sub_type'				=>	'PrepaidExpenses',
				'account_sub_type_display_name'	=>	'Prepaid Expenses',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Other Current Asset',
				'account_type_display_name'		=>	'Other Current Assets',
				'account_sub_type'				=>	'Retainage',
				'account_sub_type_display_name'	=>	'Retainage',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Other Current Asset',
				'account_type_display_name'		=>	'Other Current Assets',
				'account_sub_type'				=>	'UndepositedFunds',
				'account_sub_type_display_name'	=>	'Undeposited Funds',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Fixed Asset',
				'account_type_display_name'		=>	'Fixed Assets',
				'account_sub_type'				=>	'AccumulatedAmortization',
				'account_sub_type_display_name'	=>	'Accumulated Amortization',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Fixed Asset',
				'account_type_display_name'		=>	'Fixed Assets',
				'account_sub_type'				=>	'AccumulatedDepletion',
				'account_sub_type_display_name'	=>	'Accumulated Depletion',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Fixed Asset',
				'account_type_display_name'		=>	'Fixed Assets',
				'account_sub_type'				=>	'AccumulatedDepreciation',
				'account_sub_type_display_name'	=>	'Accumulated Depreciation',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Fixed Asset',
				'account_type_display_name'		=>	'Fixed Assets',
				'account_sub_type'				=>	'Buildings',
				'account_sub_type_display_name'	=>	'Buildings',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Fixed Asset',
				'account_type_display_name'		=>	'Fixed Assets',
				'account_sub_type'				=>	'DepletableAssets',
				'account_sub_type_display_name'	=>	'Depletable Assets',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Fixed Asset',
				'account_type_display_name'		=>	'Fixed Assets',
				'account_sub_type'				=>	'FixedAssetComputers',
				'account_sub_type_display_name'	=>	'Fixed Asset Computers',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Fixed Asset',
				'account_type_display_name'		=>	'Fixed Assets',
				'account_sub_type'				=>	'FixedAssetCopiers',
				'account_sub_type_display_name'	=>	'Fixed Asset Copiers',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Fixed Asset',
				'account_type_display_name'		=>	'Fixed Assets',
				'account_sub_type'				=>	'FixedAssetFurniture',
				'account_sub_type_display_name'	=>	'Fixed Asset Furniture',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Fixed Asset',
				'account_type_display_name'		=>	'Fixed Assets',
				'account_sub_type'				=>	'FixedAssetPhone',
				'account_sub_type_display_name'	=>	'Fixed Asset Phone',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Fixed Asset',
				'account_type_display_name'		=>	'Fixed Assets',
				'account_sub_type'				=>	'FixedAssetPhotoVideo',
				'account_sub_type_display_name'	=>	'Fixed Asset Photo Video',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Fixed Asset',
				'account_type_display_name'		=>	'Fixed Assets',
				'account_sub_type'				=>	'FixedAssetSoftware',
				'account_sub_type_display_name'	=>	'Fixed Asset Software',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Fixed Asset',
				'account_type_display_name'		=>	'Fixed Assets',
				'account_sub_type'				=>	'FixedAssetOtherToolsEquipment',
				'account_sub_type_display_name'	=>	'Fixed Asset Other Tools Equipment',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Fixed Asset',
				'account_type_display_name'		=>	'Fixed Assets',
				'account_sub_type'				=>	'FurnitureAndFixtures',
				'account_sub_type_display_name'	=>	'Furniture And Fixtures',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Fixed Asset',
				'account_type_display_name'		=>	'Fixed Assets',
				'account_sub_type'				=>	'IntangibleAssets',
				'account_sub_type_display_name'	=>	'Intangible Assets',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Fixed Asset',
				'account_type_display_name'		=>	'Fixed Assets',
				'account_sub_type'				=>	'Land',
				'account_sub_type_display_name'	=>	'Land',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Fixed Asset',
				'account_type_display_name'		=>	'Fixed Assets',
				'account_sub_type'				=>	'LeaseholdImprovements',
				'account_sub_type_display_name'	=>	'Leasehold Improvements',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Fixed Asset',
				'account_type_display_name'		=>	'Fixed Assets',
				'account_sub_type'				=>	'MachineryAndEquipment',
				'account_sub_type_display_name'	=>	'Machinery & Equipment',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Fixed Asset',
				'account_type_display_name'		=>	'Fixed Assets',
				'account_sub_type'				=>	'OtherFixedAssets',
				'account_sub_type_display_name'	=>	'Other fixed assets',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Fixed Asset',
				'account_type_display_name'		=>	'Fixed Assets',
				'account_sub_type'				=>	'Vehicles',
				'account_sub_type_display_name'	=>	'Vehicles',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Other Asset',
				'account_type_display_name'		=>	'Other Assets',
				'account_sub_type'				=>	'AccumulatedAmortizationOfOtherAssets',
				'account_sub_type_display_name'	=>	'Accumulated Amortization Of Other Assets',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Other Asset',
				'account_type_display_name'		=>	'Other Assets',
				'account_sub_type'				=>	'Goodwill',
				'account_sub_type_display_name'	=>	'Goodwill',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Other Asset',
				'account_type_display_name'		=>	'Other Assets',
				'account_sub_type'				=>	'Licenses',
				'account_sub_type_display_name'	=>	'Licenses',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Other Asset',
				'account_type_display_name'		=>	'Other Assets',
				'account_sub_type'				=>	'LeaseBuyout',
				'account_sub_type_display_name'	=>	'Lease Buyout',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Other Asset',
				'account_type_display_name'		=>	'Other Assets',
				'account_sub_type'				=>	'OrganizationalCosts',
				'account_sub_type_display_name'	=>	'Organizational Costs',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Other Asset',
				'account_type_display_name'		=>	'Other Assets',
				'account_sub_type'				=>	'OtherLongTermAssets',
				'account_sub_type_display_name'	=>	'Other Long-term Assets',
			],
			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Other Asset',
				'account_type_display_name'		=>	'Other Assets',
				'account_sub_type'				=>	'SecurityDeposits',
				'account_sub_type_display_name'	=>	'Security Deposits',
			],

			[
				'classification' 		=>  'ASSET',
				'account_type'			  		=>	'Accounts Receivable',
				'account_type_display_name'		=>	'Accounts receivable (A/R)',
				'account_sub_type'				=>	'AccountsReceivable',
				'account_sub_type_display_name'	=>	'Accounts Receivable (A/R)',
			],
			[
				'classification' 		=>  'EQUITY',
				'account_type'			  		=>	'Equity',
				'account_type_display_name'		=>	'Equity',
				'account_sub_type'				=>	'AccumulatedAdjustment',
				'account_sub_type_display_name'	=>	'Accumulated Adjustment',
			],
			[
				'classification' 		=>  'EQUITY',
				'account_type'			  		=>	'Equity',
				'account_type_display_name'		=>	'Equity',
				'account_sub_type'				=>	'CommonStock',
				'account_sub_type_display_name'	=>	'Common Stock',
			],
			[
				'classification' 		=>  'EQUITY',
				'account_type'			  		=>	'Equity',
				'account_type_display_name'		=>	'Equity',
				'account_sub_type'				=>	'EstimatedTaxes',
				'account_sub_type_display_name'	=>	'Estimated Taxes',
			],
			[
				'classification' 		=>  'EQUITY',
				'account_type'			  		=>	'Equity',
				'account_type_display_name'		=>	'Equity',
				'account_sub_type'				=>	'Healthcare',
				'account_sub_type_display_name'	=>	'Healthcare',
			],
			[
				'classification' 		=>  'EQUITY',
				'account_type'			  		=>	'Equity',
				'account_type_display_name'		=>	'Equity',
				'account_sub_type'				=>	'OpeningBalanceEquity',
				'account_sub_type_display_name'	=>	'Opening Balance Equity',
			],
			[
				'classification' 		=>  'EQUITY',
				'account_type'			  		=>	'Equity',
				'account_type_display_name'		=>	'Equity',
				'account_sub_type'				=>	'OwnersEquity',
				'account_sub_type_display_name'	=>	'Owner`s Equity',
			],
			[
				'classification' 		=>  'EQUITY',
				'account_type'			  		=>	'Equity',
				'account_type_display_name'		=>	'Equity',
				'account_sub_type'				=>	'PartnersEquity',
				'account_sub_type_display_name'	=>	'Partner`s Equity',
			],
			[
				'classification' 		=>  'EQUITY',
				'account_type'			  		=>	'Equity',
				'account_type_display_name'		=>	'Equity',
				'account_sub_type'				=>	'PaidInCapitalOrSurplus',
				'account_sub_type_display_name'	=>	'Paid-InCapital or Surplus',
			],
			[
				'classification' 		=>  'EQUITY',
				'account_type'			  		=>	'Equity',
				'account_type_display_name'		=>	'Equity',
				'account_sub_type'				=>	'PartnerContributions',
				'account_sub_type_display_name'	=>	'Partner Contributions',
			],
			[
				'classification' 		=>  'EQUITY',
				'account_type'			  		=>	'Equity',
				'account_type_display_name'		=>	'Equity',
				'account_sub_type'				=>	'PartnerDistributions',
				'account_sub_type_display_name'	=>	'Partner Distributions',
			],
			[
				'classification' 		=>  'EQUITY',
				'account_type'			  		=>	'Equity',
				'account_type_display_name'		=>	'Equity',
				'account_sub_type'				=>	'PreferredStock',
				'account_sub_type_display_name'	=>	'Preferred Stock',
			],
			[
				'classification' 		=>  'EQUITY',
				'account_type'			  		=>	'Equity',
				'account_type_display_name'		=>	'Equity',
				'account_sub_type'				=>	'PersonalIncome',
				'account_sub_type_display_name'	=>	'Personal Income',
			],
			[
				'classification' 		=>  'EQUITY',
				'account_type'			  		=>	'Equity',
				'account_type_display_name'		=>	'Equity',
				'account_sub_type'				=>	'PersonalExpense',
				'account_sub_type_display_name'	=>	'Personal Expense',
			],
			[
				'classification' 		=>  'EQUITY',
				'account_type'			  		=>	'Equity',
				'account_type_display_name'		=>	'Equity',
				'account_sub_type'				=>	'RetainedEarnings',
				'account_sub_type_display_name'	=>	'Retained Earnings',
			],
			[
				'classification' 		=>  'EQUITY',
				'account_type'			  		=>	'Equity',
				'account_type_display_name'		=>	'Equity',
				'account_sub_type'				=>	'TreasuryStock',
				'account_sub_type_display_name'	=>	'Treasury Stock',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Expense',
				'account_type_display_name'		=>	'Expenses',
				'account_sub_type'				=>	'AdvertisingPromotional',
				'account_sub_type_display_name'	=>	'Advertising/Promotional',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Expense',
				'account_type_display_name'		=>	'Expenses',
				'account_sub_type'				=>	'Auto',
				'account_sub_type_display_name'	=>	'Auto',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Expense',
				'account_type_display_name'		=>	'Expenses',
				'account_sub_type'				=>	'BadDebts',
				'account_sub_type_display_name'	=>	'Bad Debts',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Expense',
				'account_type_display_name'		=>	'Expenses',
				'account_sub_type'				=>	'BankCharges',
				'account_sub_type_display_name'	=>	'Bank Charges',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Expense',
				'account_type_display_name'		=>	'Expenses',
				'account_sub_type'				=>	'CostOfLabor',
				'account_sub_type_display_name'	=>	'Cost Of Labor',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Expense',
				'account_type_display_name'		=>	'Expenses',
				'account_sub_type'				=>	'CharitableContributions',
				'account_sub_type_display_name'	=>	'Charitable Contributions',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Expense',
				'account_type_display_name'		=>	'Expenses',
				'account_sub_type'				=>	'DuesSubscriptions',
				'account_sub_type_display_name'	=>	'Dues & Subscriptions',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Expense',
				'account_type_display_name'		=>	'Expenses',
				'account_sub_type'				=>	'Entertainment',
				'account_sub_type_display_name'	=>	'Entertainment',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Expense',
				'account_type_display_name'		=>	'Expenses',
				'account_sub_type'				=>	'EntertainmentMeals',
				'account_sub_type_display_name'	=>	'Entertainment Meals',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Expense',
				'account_type_display_name'		=>	'Expenses',
				'account_sub_type'				=>	'EquipmentRental',
				'account_sub_type_display_name'	=>	'Equipment Rental',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Expense',
				'account_type_display_name'		=>	'Expenses',
				'account_sub_type'				=>	'FinanceCosts',
				'account_sub_type_display_name'	=>	'Finance Costs',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Expense',
				'account_type_display_name'		=>	'Expenses',
				'account_sub_type'				=>	'Insurance',
				'account_sub_type_display_name'	=>	'Insurance',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Expense',
				'account_type_display_name'		=>	'Expenses',
				'account_sub_type'				=>	'InterestPaid',
				'account_sub_type_display_name'	=>	'Interest Paid',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Expense',
				'account_type_display_name'		=>	'Expenses',
				'account_sub_type'				=>	'LegalProfessionalFees',
				'account_sub_type_display_name'	=>	'Legal & Professional Fees',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Expense',
				'account_type_display_name'		=>	'Expenses',
				'account_sub_type'				=>	'OfficeExpenses',
				'account_sub_type_display_name'	=>	'OfficeExpenses',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Expense',
				'account_type_display_name'		=>	'Expenses',
				'account_sub_type'				=>	'OfficeGeneralAdministrativeExpenses',
				'account_sub_type_display_name'	=>	'Office/General Administrative Expenses',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Expense',
				'account_type_display_name'		=>	'Expenses',
				'account_sub_type'				=>	'OtherBusinessExpenses',
				'account_sub_type_display_name'	=>	'Other Business Expenses',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Expense',
				'account_type_display_name'		=>	'Expenses',
				'account_sub_type'				=>	'OtherMiscellaneousServiceCost',
				'account_sub_type_display_name'	=>	'Other Miscellaneous Service Cost',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Expense',
				'account_type_display_name'		=>	'Expenses',
				'account_sub_type'				=>	'PromotionalMeals',
				'account_sub_type_display_name'	=>	'Promotional Meals',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Expense',
				'account_type_display_name'		=>	'Expenses',
				'account_sub_type'				=>	'PayrollExpenses',
				'account_sub_type_display_name'	=>	'Payroll Expenses',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Expense',
				'account_type_display_name'		=>	'Expenses',
				'account_sub_type'				=>	'RentOrLeaseOfBuildings',
				'account_sub_type_display_name'	=>	'Rent or Lease Of Buildings',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Expense',
				'account_type_display_name'		=>	'Expenses',
				'account_sub_type'				=>	'RepairMaintenance',
				'account_sub_type_display_name'	=>	'Repair & Maintenance',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Expense',
				'account_type_display_name'		=>	'Expenses',
				'account_sub_type'				=>	'ShippingFreightDelivery',
				'account_sub_type_display_name'	=>	'Shipping,Freight & Delivery',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Expense',
				'account_type_display_name'		=>	'Expenses',
				'account_sub_type'				=>	'SuppliesMaterials',
				'account_sub_type_display_name'	=>	'Supplies & Materials',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Expense',
				'account_type_display_name'		=>	'Expenses',
				'account_sub_type'				=>	'Travel',
				'account_sub_type_display_name'	=>	'Travel',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Expense',
				'account_type_display_name'		=>	'Expenses',
				'account_sub_type'				=>	'TravelMeals',
				'account_sub_type_display_name'	=>	'Travel Meals',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Expense',
				'account_type_display_name'		=>	'Expenses',
				'account_sub_type'				=>	'TaxesPaid',
				'account_sub_type_display_name'	=>	'Taxes Paid',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Expense',
				'account_type_display_name'		=>	'Expenses',
				'account_sub_type'				=>	'UnappliedCashBillPaymentExpense',
				'account_sub_type_display_name'	=>	'Unapplied Cash Bill Payment Expense',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Expense',
				'account_type_display_name'		=>	'Expenses',
				'account_sub_type'				=>	'Utilities',
				'account_sub_type_display_name'	=>	'Utilities',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Other Expense',
				'account_type_display_name'		=>	'Other Expense',
				'account_sub_type'				=>	'Amortization',
				'account_sub_type_display_name'	=>	'Amortization',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Other Expense',
				'account_type_display_name'		=>	'Other Expense',
				'account_sub_type'				=>	'Depreciation',
				'account_sub_type_display_name'	=>	'Depreciation',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Other Expense',
				'account_type_display_name'		=>	'Other Expense',
				'account_sub_type'				=>	'ExchangeGainOrLoss',
				'account_sub_type_display_name'	=>	'Exchange Gain Or Loss',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Other Expense',
				'account_type_display_name'		=>	'Other Expense',
				'account_sub_type'				=>	'GasAndFuel',
				'account_sub_type_display_name'	=>	'Gas And Fuel',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Other Expense',
				'account_type_display_name'		=>	'Other Expense',
				'account_sub_type'				=>	'HomeOffice',
				'account_sub_type_display_name'	=>	'Home Office',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Other Expense',
				'account_type_display_name'		=>	'Other Expense',
				'account_sub_type'				=>	'HomeOwnerRentalInsurance',
				'account_sub_type_display_name'	=>	'HomeOwner Rental Insurance',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Other Expense',
				'account_type_display_name'		=>	'Other Expense',
				'account_sub_type'				=>	'MortgageInterest',
				'account_sub_type_display_name'	=>	'Mortgage Interest',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Other Expense',
				'account_type_display_name'		=>	'Other Expense',
				'account_sub_type'				=>	'OtherHomeOfficeExpenses',
				'account_sub_type_display_name'	=>	'Other Home Office Expenses',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Other Expense',
				'account_type_display_name'		=>	'Other Expense',
				'account_sub_type'				=>	'OtherMiscellaneousExpense',
				'account_sub_type_display_name'	=>	'Other Miscellaneous Expense',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Other Expense',
				'account_type_display_name'		=>	'Other Expense',
				'account_sub_type'				=>	'OtherVehicleExpenses',
				'account_sub_type_display_name'	=>	'Other Vehicle Expenses',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Other Expense',
				'account_type_display_name'		=>	'Other Expense',
				'account_sub_type'				=>	'PenaltiesSettlements',
				'account_sub_type_display_name'	=>	'Penalties & Settlements',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Other Expense',
				'account_type_display_name'		=>	'Other Expense',
				'account_sub_type'				=>	'ParkingAndTolls',
				'account_sub_type_display_name'	=>	'Parking And Tolls',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Other Expense',
				'account_type_display_name'		=>	'Other Expense',
				'account_sub_type'				=>	'RentAndLease',
				'account_sub_type_display_name'	=>	'Rent and Lease',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Other Expense',
				'account_type_display_name'		=>	'Other Expense',
				'account_sub_type'				=>	'RepairsAndMaintenance',
				'account_sub_type_display_name'	=>	'Repairs and Maintenance',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Other Expense',
				'account_type_display_name'		=>	'Other Expense',
				'account_sub_type'				=>	'Utilities',
				'account_sub_type_display_name'	=>	'Utilities',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Other Expense',
				'account_type_display_name'		=>	'Other Expense',
				'account_sub_type'				=>	'Vehicle',
				'account_sub_type_display_name'	=>	'Vehicle',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Other Expense',
				'account_type_display_name'		=>	'Other Expense',
				'account_sub_type'				=>	'VehicleInsurance',
				'account_sub_type_display_name'	=>	'Vehicle Insurance',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Other Expense',
				'account_type_display_name'		=>	'Other Expense',
				'account_sub_type'				=>	'VehicleLease',
				'account_sub_type_display_name'	=>	'Vehicle Lease',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Other Expense',
				'account_type_display_name'		=>	'Other Expense',
				'account_sub_type'				=>	'VehicleLoanInterest',
				'account_sub_type_display_name'	=>	'Vehicle Loan Interest',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Other Expense',
				'account_type_display_name'		=>	'Other Expense',
				'account_sub_type'				=>	'VehicleLoan',
				'account_sub_type_display_name'	=>	'Vehicle Loan',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Other Expense',
				'account_type_display_name'		=>	'Other Expense',
				'account_sub_type'				=>	'VehicleRegistration',
				'account_sub_type_display_name'	=>	'Vehicle Registration',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Other Expense',
				'account_type_display_name'		=>	'Other Expense',
				'account_sub_type'				=>	'VehicleRepairs',
				'account_sub_type_display_name'	=>	'Vehicle Repairs',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Other Expense',
				'account_type_display_name'		=>	'Other Expense',
				'account_sub_type'				=>	'WashAndRoadServices',
				'account_sub_type_display_name'	=>	'Wash and Road Services',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Cost of Goods Sold',
				'account_type_display_name'		=>	'Cost of Goods Sold',
				'account_sub_type'				=>	'CostOfLaborCos',
				'account_sub_type_display_name'	=>	'Cost Of Labor-COS',
			],
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Cost of Goods Sold',
				'account_type_display_name'		=>	'Cost of Goods Sold',
				'account_sub_type'				=>	'EquipmentRentalCos',
				'account_sub_type_display_name'	=>	'Equipment Rental-COS',
			],	
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Cost of Goods Sold',
				'account_type_display_name'		=>	'Cost of Goods Sold',
				'account_sub_type'				=>	'OtherCostsOfServiceCos',
				'account_sub_type_display_name'	=>	'Other Costs Of Services-COS',
			],	
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Cost of Goods Sold',
				'account_type_display_name'		=>	'Cost of Goods Sold',
				'account_sub_type'				=>	'ShippingFreightDeliveryCos',
				'account_sub_type_display_name'	=>	'Shipping, Freight & Delivery-COS',
			],	
			[
				'classification' 		=>  'EXPENSE',
				'account_type'			  		=>	'Cost of Goods Sold',
				'account_type_display_name'		=>	'Cost of Goods Sold',
				'account_sub_type'				=>	'SuppliesMaterialsCogs',
				'account_sub_type_display_name'	=>	'Supplies & Materials-COGS',
			],	
			[
				'classification' 		=>  'LIABILITY',
				'account_type'			  		=>	'Accounts Payable',
				'account_type_display_name'		=>	'Accounts Payable (A/P)',
				'account_sub_type'				=>	'AccountsPayable',
				'account_sub_type_display_name'	=>	'Accounts Payable (A/P)',
			],
			[
				'classification' 		=>  'LIABILITY',
				'account_type'			  		=>	'Credit Card',
				'account_type_display_name'		=>	'Credit Card',
				'account_sub_type'				=>	'CreditCard',
				'account_sub_type_display_name'	=>	'Credit Card',
			],	
			[
				'classification' 		=>  'LIABILITY',
				'account_type'			  		=>	'Long Term Liability',
				'account_type_display_name'		=>	'Long Term Liabilities',
				'account_sub_type'				=>	'NotesPayable',
				'account_sub_type_display_name'	=>	'Notes Payable',
			],	
			[
				'classification' 		=>  'LIABILITY',
				'account_type'			  		=>	'Long Term Liability',
				'account_type_display_name'		=>	'Long Term Liabilities',
				'account_sub_type'				=>	'OtherLongTermLiabilities',
				'account_sub_type_display_name'	=>	'Other Long Term Liabilities',
			],		
			[
				'classification' 		=>  'LIABILITY',
				'account_type'			  		=>	'Long Term Liability',
				'account_type_display_name'		=>	'Long Term Liabilities',
				'account_sub_type'				=>	'ShareholderNotesPayable',
				'account_sub_type_display_name'	=>	'Shareholder Notes Payable',
			],
			[
				'classification' 		=>  'LIABILITY',
				'account_type'			  		=>	'Other Current Liability',
				'account_type_display_name'		=>	'Other Current Liabilities',
				'account_sub_type'				=>	'FederalIncomeTaxPayable',
				'account_sub_type_display_name'	=>	'Federal Income Tax Payable',
			],	
			[
				'classification' 		=>  'LIABILITY',
				'account_type'			  		=>	'Other Current Liability',
				'account_type_display_name'		=>	'Other Current Liabilities',
				'account_sub_type'				=>	'InsurancePayable',
				'account_sub_type_display_name'	=>	'Insurance Payable',
			],	
			[
				'classification' 		=>  'LIABILITY',
				'account_type'			  		=>	'Other Current Liability',
				'account_type_display_name'		=>	'Other Current Liabilities',
				'account_sub_type'				=>	'LineOfCredit',
				'account_sub_type_display_name'	=>	'Line Of Credit',
			],	
			[
				'classification' 		=>  'LIABILITY',
				'account_type'			  		=>	'Other Current Liability',
				'account_type_display_name'		=>	'Other Current Liabilities',
				'account_sub_type'				=>	'LoanPayable',
				'account_sub_type_display_name'	=>	'Loan Payable',
			],
			[
				'classification' 		=>  'LIABILITY',
				'account_type'			  		=>	'Other Current Liability',
				'account_type_display_name'		=>	'Other Current Liabilities',
				'account_sub_type'				=>	'OtherCurrentLiabilities',
				'account_sub_type_display_name'	=>	'Other Current Liabilities',
			],	
			[
				'classification' 		=>  'LIABILITY',
				'account_type'			  		=>	'Other Current Liability',
				'account_type_display_name'		=>	'Other Current Liabilities',
				'account_sub_type'				=>	'PayrollClearing',
				'account_sub_type_display_name'	=>	'Payroll Clearing',
			],	
			[
				'classification' 		=>  'LIABILITY',
				'account_type'			  		=>	'Other Current Liability',
				'account_type_display_name'		=>	'Other Current Liabilities',
				'account_sub_type'				=>	'PayrollTaxPayable',
				'account_sub_type_display_name'	=>	'Payroll Tax Payable',
			],	
			[
				'classification' 		=>  'LIABILITY',
				'account_type'			  		=>	'Other Current Liability',
				'account_type_display_name'		=>	'Other Current Liabilities',
				'account_sub_type'				=>	'PrepaidExpensesPayable',
				'account_sub_type_display_name'	=>	'Prepaid Expenses Payable',
			],	
			[
				'classification' 		=>  'LIABILITY',
				'account_type'			  		=>	'Other Current Liability',
				'account_type_display_name'		=>	'Other Current Liabilities',
				'account_sub_type'				=>	'RentsInTrustLiability',
				'account_sub_type_display_name'	=>	'Rents in trust-Liability',
			],	
			[
				'classification' 		=>  'LIABILITY',
				'account_type'			  		=>	'Other Current Liability',
				'account_type_display_name'		=>	'Other Current Liabilities',
				'account_sub_type'				=>	'SalesTaxPayable',
				'account_sub_type_display_name'	=>	'Sales Tax Payable',
			],	
			[
				'classification' 		=>  'LIABILITY',
				'account_type'			  		=>	'Other Current Liability',
				'account_type_display_name'		=>	'Other Current Liabilities',
				'account_sub_type'				=>	'StateLocalIncomeTaxPayable',
				'account_sub_type_display_name'	=>	'State/Local Income Tax Payable',
			],
			[
				'classification' 		=>  'LIABILITY',
				'account_type'			  		=>	'Other Current Liability',
				'account_type_display_name'		=>	'Other Current Liabilities',
				'account_sub_type'				=>	'TrustAccountsLiabilities',
				'account_sub_type_display_name'	=>	'Trust Accounts-Liabilities',
			],	
			[
				'classification' 		=>  'LIABILITY',
				'account_type'			  		=>	'Other Current Liability',
				'account_type_display_name'		=>	'Other Current Liabilities',
				'account_sub_type'				=>	'Undistributed Tips',
				'account_sub_type_display_name'	=>	'Undistributed Tips',
			],	
			[
				'classification' 		=>  'REVENUE',
				'account_type'			  		=>	'Income',
				'account_type_display_name'		=>	'Income',
				'account_sub_type'				=>	'DiscountsRefundsGiven',
				'account_sub_type_display_name'	=>	'Discounts/Refunds Given',
			],
			[
				'classification' 		=>  'REVENUE',
				'account_type'			  		=>	'Income',
				'account_type_display_name'		=>	'Income',
				'account_sub_type'				=>	'NonProfitIncome',
				'account_sub_type_display_name'	=>	'Non-Profit Income',
			],
			[
				'classification' 		=>  'REVENUE',
				'account_type'			  		=>	'Income',
				'account_type_display_name'		=>	'Income',
				'account_sub_type'				=>	'OtherPrimaryIncome',
				'account_sub_type_display_name'	=>	'Other-Primary Income',
			],
			[
				'classification' 		=>  'REVENUE',
				'account_type'			  		=>	'Income',
				'account_type_display_name'		=>	'Income',
				'account_sub_type'				=>	'SalesOfProductIncome',
				'account_sub_type_display_name'	=>	'Sales Of Product Income',
			],
			[
				'classification' 		=>  'REVENUE',
				'account_type'			  		=>	'Income',
				'account_type_display_name'		=>	'Income',
				'account_sub_type'				=>	'ServiceFeeIncome',
				'account_sub_type_display_name'	=>	'Service/Fee Income',
			],
			[
				'classification' 		=>  'REVENUE',
				'account_type'			  		=>	'Income',
				'account_type_display_name'		=>	'Income',
				'account_sub_type'				=>	'UnappliedCashPaymentIncome',
				'account_sub_type_display_name'	=>	'Unapplied Cash Payment Income',
			],
			[
				'classification' 		=>  'REVENUE',
				'account_type'			  		=>	'Other Income',
				'account_type_display_name'		=>	'Other Income',
				'account_sub_type'				=>	'DividendIncome',
				'account_sub_type_display_name'	=>	'Dividend Income',
			],
			[
				'classification' 		=>  'REVENUE',
				'account_type'			  		=>	'Other Income',
				'account_type_display_name'		=>	'Other Income',
				'account_sub_type'				=>	'InterestEarned',
				'account_sub_type_display_name'	=>	'Interest Earned',
			],
			[
				'classification' 		=>  'REVENUE',
				'account_type'			  		=>	'Other Income',
				'account_type_display_name'		=>	'Other Income',
				'account_sub_type'				=>	'OtherInvestmentIncome',
				'account_sub_type_display_name'	=>	'Other Investment Income',
			],
			[
				'classification' 		=>  'REVENUE',
				'account_type'			  		=>	'Other Income',
				'account_type_display_name'		=>	'Other Income',
				'account_sub_type'				=>	'OtherMiscellaneousIncome',
				'account_sub_type_display_name'	=>	'Other Miscellaneous Income',
			],
			[
				'classification' 		=>  'REVENUE',
				'account_type'			  		=>	'Other Income',
				'account_type_display_name'		=>	'Other Income',
				'account_sub_type'				=>	'TaxExemptInterest',
				'account_sub_type_display_name'	=>	'Tax-Exempt Interest',
			],
		];

		 foreach ($accountTypes as $data) {
			FinancialAccountTypes::create($data);
		}
	}

}