<?php
return array(
	"default_error" => array(
		'message' => 'System Synch Error',
	    'error_type' => 'Default Error',
	    'error_code' => 'System_Error',
	    'details' => 'Some unknown error occured',
	    'remedy' => 'If you can not make out the solution from the error details Please contact the JP customer success team for further information',
	    'explanation' => 'Synch failed due to the above error.',
	),
	"remedy" => array(

		'duplicate_customer'  => '<ol>
            <li> Map - This will link these records and duplication would be avoided</li>
            <li> Mark as different - This will mark both the records as different and hence a new corresponding record would be created in QBO</li>
            </ol>',
		'6210' 	=> '<ol>
                <li>Open the accounting period in QBO for the required dates to allow this transaction to synch. </li>
                <li>Update the date on the transaction in JobProgress to the current open period for accounting in QBO.</li>
            </ol>',
		'6140' 	=> '<ol>
                <li>Delete the orignal transaction from QBO and then edit and save transaction in JP without making any change to trigger the synch </li>
                <li>Delete the transaction from JP and create a new transaction if you intent to generate a new transaction number</li>
                <li>Use Synch manager -> Mapping tab to synchronize the transactions </li>
            </ol>',
		'2500' =>'Some object reference by this record has been made inactive on QBO it could by anything from Customer, Vendor, Product/Service, Accounts etc.',
		'5030' => 'To be able to use those features in JP and sync to QuickBooks Online, please upgrade to QuickBooks Plus. Please see the QuickBooks <a href="https://quickbooks.intuit.com/oa/online/" target="_blank">Online Feature Comparison Chart</a> to determine the subscription you will need to sync with jP, based on the features you would like to use.',
		'6480' => '<ol>
            <li>Manually delete the bill in QuickBooks Online</li>
            <li>Contact Customer Support to request the error be cleared</li>
		</ol>',
		'6540' => 'This transaction has been deposited. If you want to change or delete it, you must edit the deposit it appears on and remove it first',
	),
	"explanation" => array(

		'duplicate_customer'  	=> 'This customer seems to already exist in QBO and to avoid duplicating it, synching has not been performed. Please use the Mapping tab in Synch Manager to take one of the suggested solutions below ',
		'6210' 					=> 'This error occurs when a transaction that is trying to sync to QuickBooks Online (QBO) is dated in a period that is closed in QBO.',
		'6140' 					=> 'Transaction number allocated to this transaction by JP is already taken by some other transaction in QBO
            Since transaction numbers are generated by JP are unique and prefixed with JP, the only scenario for this error can be if someone manually enters the same transaction number in QBO.
            QBO allows that manual entry of transaction number if you turn on <b>"Custom transaction numbers" preference</b>
            ',
		'5030'					=> 'This error occurs when using some features in Jobprogress.com, such as billable expenses and class/division tracking, as the QuickBooks Online Essentials subscription does not support these features.',
		'2500' 					=> '<ol>
			<li> If it is invoice that is failing because the Product/Service has been deleted then you can either restore the Product/Service in QBO or you can change the Work Type of the invoice in JP </li>
		<ol>',
		'6480' => 'You can not delete this transaction because it is matched to a transaction that was downloaded into a different account',
		'6540' => 'This transaction has been deposited. If you want to change or delete it, you must edit the deposit it appears on and remove it first',
	),
);